services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: leaf_chatbot

  leaf_chatbot:
    image: bogdanjovanovic/leaf-chatbot:0.0.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/leaf_chatbot
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LEAF_MARKDOWN_DIR: /leaf-docs
    volumes:
      - ./leaf-docs:/leaf-docs
