services:
  db:
    container_name: db
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: leaf_chatbot
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - db:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8000:8080"
#    networks:
#      - botnetwork
#
#networks:
#  botnetwork:
#    name: langchainnetwork
#    driver: bridge
#volumes:
#  db:
