spring:
  application:
    name: leaf-chatbot
  datasource:
    url: jdbc:postgresql://localhost:5432/leaf_chatbot
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        max-document-batch-size: 10000
        initialize-schema: true
    retry:
      max-attempts: 3
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 1536
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
