spring:
  application:
    name: leaf-chatbot
  datasource:
    url: jdbc:postgresql://localhost:5432/leaf_chatbot
    username: postgres
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
    chat:
      client:
        enabled: false
