spring:
  application:
    name: leaf-chatbot
  datasource:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: optional:classpath:schema.sql # optional means that app will start even if the file doesn't exist
  ai:
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        max-document-batch-size: 10000
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 1536
    chat:
      client:
        enabled: false
